# Type: WayPoint
"patrol": ["WayPoint4", "WayPoint5", "WayPoint10", "WayPoint22", "WayPoint23", "WayPoint24", "WayPoint25", "WayPoint1", "Station"]
"observe": ["WayPoint17", "WayPoint18", "WayPoint19", "WayPoint20", "WayPoint21", "WayPoint22", "Station", "WayPoint3", "WayPoint10"]
# "observe": ["WayPoint18", "Station"]

